# Generated by Django 4.2.2 on 2023-06-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('name_description', models.CharField()),
                ('background_image', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='games',
            field=models.ManyToManyField(to='core.game'),
        ),
    ]
